### ISSUE TITLE
Roadmap to v4

### ISSUE THREAD

**Issue by schoero** [schoero/swissqrbill#414]
This issue is meant to summarize the planned changes for v4 and track its progress.

Goals:

 - More flexibility: 
   - [x] #388 
   - [x] #391 
   - [x] #397 
   - [x] #405 
   - [x] #411 
   - [x] https://github.com/schoero/SwissQRBill/pull/388#issuecomment-1563923384
   - [x] #417
   - [x] #420 
 - [x] Automated testing
 - [x] Auto generating documentation
 - [x] Automatic versioning, changelog generation and releases
 - [x] General cleanup

Todo:

- [x] Don't directly extend PDFKit. Instead create a new  `QRBill` class that attaches to an existing PDFKit instance. https://github.com/schoero/SwissQRBill/pull/386#issuecomment-1236159057.
- [x] Create a separate `Table` class for the [`addTable()`](https://github.com/schoero/SwissQRBill/blob/57d760235995b927c4ec2cee0a4a751c7ae845ab/src/pdf/extended-pdf.ts#L151) function, that attaches to an existing PDFKit instance.
- [ ] ~Keep an existing `SwissQRBill` class, that extends both of the other classes, as well as PDFKit for backwards compatibility.~
- [x] Autogenerate changelog
- [x] Improve testing
- [x] Autogenerate documentation.  
- [ ] General cleanup:
  - [ ] ~Improve TypeScript typings.~
  - [x] Rename repository to lowercase `swissqrbill`
  - [x] Rename `master` branch to `main`
- [x] Update [how to guide](https://github.com/schoero/SwissQRBill/blob/master/doc/how-to-create-a-complete-bill.md)
- [x] Create comprehensive migration guide for all users
  - [x] users of prebuilt bundle.
  - [x] users of html script tag.
  - [x] users of PDF events.
  - [x] users with custom bundling.
  - [x] users of common js module.

**Comment by skch-17** [comment]
@schoero Just wanted to let you know that currently in v4 the addContent (swissCrossBackground and scissors) seams not to work. At least in my version. I changed it back to doc.path and it worked again. Careful the strings are not an svg path they need to be replaced as well. (Master branch has the right thing)

**Comment by schoero** [comment]
Thanks for pointing that out @skch-17. We switched to `addContent` for performance reasons #384. But the scissors and swiss cross contained invalid data. I have fixed it now and also improved the testing behavior, so that this kind of problems will be caught in future.

**Comment by schoero** [comment]
SwissQRBill v4.0.0 is now finally released 🎉
